import json
import datetime
from dateutil import parser

from processing.revenue import calculate_revenue_data_daily
from utility.api_manager import manager
from utility.util import json_serialize_datetime
from tqdm import tqdm


def get_turnovers():
    result = []

    for user in tqdm(manager.users, desc="Collecting turnovers from sold players"):
        transfers = []

        for buy in manager.get_transfers_raw(user['i']):
            if parser.parse(buy['dt']) < manager.start:
                print("too old")
                continue

            transfer_type = 'buy' if buy['tty'] == 1 else 'sell'

            if 'othnm' in buy:
                trade_partner = buy['othnm']
            else:
                trade_partner = 'Computer'

            transfers.append({'date': parser.parse(buy['dt']),
                              'first_name': buy['pn'],
                              'last_name': buy['pn'],
                              'value': buy['trp'],
                              'type': transfer_type,
                              'trade_partner': trade_partner,
                              'team_id': buy['tid'],
                              'player_id': buy['pi'],
                              'user': user['n']})

        # Remove duplicates given by api
        transfers = list({frozenset(item.items()): item for item in transfers}.values())

        transfers.reverse()

        turnovers = []

        for i, buy_transfer in enumerate(transfers):
            if buy_transfer['type'] == 'sell':
                continue

            for sell_transfer in transfers[i:]:
                if sell_transfer['type'] == 'buy':
                    continue

                if sell_transfer['player_id'] == buy_transfer['player_id'] :# and sell_transfer['user'] == buy_transfer['trade_partner']:
                    turnovers.append((buy_transfer, sell_transfer))
                    break
                    
        # Revenue generated by randomly assigned players
        for transfer in transfers:
            if transfer['type'] == 'buy':
                continue

            if transfer not in [turnover[1] for turnover in turnovers]:
                
                
                player_history = manager.get(f"/leagues/{manager.leagueid}/players/{transfer['player_id']}/transferHistory")["it"]
                
                og_money = None
                for event in player_history:
                    if manager.start == parser.parse(event.get('dt')) and event['t'] == 0:
                        og_money = event['trp']
                        print("found a player")
                        break
                
                if og_money is None:
                    print(
                        f"Could not find original transfer price for "
                        f"{transfer['user']} / {transfer['last_name']}"
                    )
                    continue
                
                
                date = manager.start
                buy_transfer = {'date': date,
                                'first_name': transfer['first_name'],
                                'last_name': transfer['last_name'],
                                'value': og_money,
                                'type': 'buy',
                                'trade_partner': 'Computer',
                                'team_id': transfer['team_id'],
                                'player_id': transfer['player_id'],
                                'user': transfer['user']}

                turnovers.append((buy_transfer, transfer))

        result = result + turnovers

    with open('./data/turnovers.json', 'w') as f:
        f.writelines(json.dumps(result, default=json_serialize_datetime))

    calculate_revenue_data_daily(result)
